# Generated by Django 5.2 on 2026-05-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tech_model',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
